version: '3'

services:
  wolontariusze:
    image: 'wilczynski87/wolontariusze:latest'
    restart: always
    ports:
      - "327:327"
    build:
      context: .
    container_name: wolontariusze
    depends_on:
      - dbwolontariusze
    environment:
      - SPRING_DATASOURCE_URL=r2dbc:postgresql://dbwolontariusze:5432/wolontariusze
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - PORT=327
      - api=ie
    healthcheck:
      test: curl --fail http://wolontariusze:327 || exit 1
      interval: 300s
      timeout: 10s
      retries: 3
          
  dbwolontariusze:
    image: 'postgres:latest'
    restart: always
    container_name: dbwolontariusze
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wolontariusze
    ports:
      - "5432:5432"
    volumes: 
      - dbwolontariusze:/var/lib/postgresql/data
  
  ie:
    image: 'ie:latest'
    restart: always
    container_name: ie
    depends_on:
      - dbwolontariusze
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbwolontariusze:5432/wolontariusze
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - PORT=328
    ports:
      - "328:328"
    healthcheck:
      test: curl --fail http://localhost:327 || exit 1
      interval: 300s
      timeout: 10s
      retries: 3

  pgbackups:
    container_name: Backup
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ./backup:/backups
    links:
      - dbwolontariusze:dbwolontariusze
    depends_on:
      - dbwolontariusze
    environment:
      - POSTGRES_HOST=dbwolontariusze
      - POSTGRES_DB=wolontariusze
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@every 0h30m00s
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=81

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    ports: 
      - "30327:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=ppp@ppp.ppp
      - PGADMIN_DEFAULT_PASSWORD=ppp

  autoheal:
      image: willfarrell/autoheal:latest
      tty: true
      restart: always
      environment:
        - AUTOHEAL_INTERVAL=60
        - AUTOHEAL_START_PERIOD=30
        - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
  
    
volumes:
  dbwolontariusze: